services:
  - type: web
    name: snapcheck-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    region: oregon
    plan: free
    branch: main
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: PORT
        value: 5000
      - key: PYTHON_VERSION
        value: 3.11.0
